### PR TITLE
Styled and organized the contact us page to new figma design!

### PR DESCRIPTION
**Pull request by aaronliuo**
comtactus

### CODE REVIEW

**Comment by aaronliuo** [comment]
So I realized that my old Navigation bar code somehow made it into this pr. Not sure what to do with this archaic piece of tech so I might go ahead and delete it at some point.

**Comment by genefu** [comment]
looks great!!! is the old nav bar code the navbar.js and rootnavigation file?

**Comment by aaronliuo** [comment]
Yes I believe so, I haven't tested it out yet. I'm too lazy right now haha

**Comment by aaronliuo** [comment]
I also realized in the shower, is there supposed to be a submit button anywhere? how do we submit this stuff

**Comment by genefu** [comment]
oh oops i didn't notice that. i'll add one in the design, and you can add it in your own time, or if backend wants to work on that together to connect it to firebase/storage/whatever, y'all can do that

**Pull request merged**
